### ISSUE TITLE
Error building for Carthage 

### ISSUE THREAD

**Issue by atturnbull** [matthewpalmer/Locksmith#139]
While using swift 3.0 I'm having an issue getting this to build with Carthage.

Getting a 

Failed to load plugin at: /Users/Me/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]

Not really sure how to fix, any help appreciated

**Comment by bennokress** [comment]
Do you have the Swift 3 branch included in your Cartfile?

> github "matthewpalmer/Locksmith" "swift-3.0"

Do you have Xcode 8.0 (…) selected under Xcode -> Preferences -> Locations -> Command Line Tools?


Those are the requirements I found out to get frameworks to work with my beta projects. Sadly Locksmith currently throws errors while installing with Carthage, but all of them seem to be related to changes in Xcode/Swift 3 since beta 4 when the branch was last updated.

**Comment by matthewpalmer** [comment]
Closing this. Thanks for the assist @bennokress—much appreciated :)
