### ISSUE TITLE
Potentially add generics support

### ISSUE THREAD

**Issue by matthewpalmer** [matthewpalmer/Locksmith#17]
Add support for generics so that users can do `Locksmith.saveData({"key": "value"}, forUserAccount: ...)` and `Locksmith.saveData("some string", forUserAccount: ...)` and `Locksmith.saveData(1234567, forUserAccount: ...)`

**Comment by benjaminhviid** [comment]
Would this also open the possibilities to store custom classes in the KeyChain? I have a class Highscore that contains ```score: Int``` and ```dateOfScore: NSDate``` that I would like to store in the KeyChain without converting them to a string and splitting it after I've retrieved them.

**Comment by matthewpalmer** [comment]
Yeah potentially. It would require your class to conform to some protocol, probably NSCoder or Hashable, but I haven't quite worked it out yet.
Is this a feature that would be helpful?

**Comment by benjaminhviid** [comment]
My class does already conform to NSCoding and it has to conform to Hashable in order to be stored in a Dictionary, so thats alright. It might be, however, that there are some limitations as to what can be stored in the Keychain? It would be very helpful to me, as I might expand on the class later on, making it a mess to convert the data back and forth to strings. 

And thanks for the frameworks, btw. It has saved me a lot of time! Cheers.
