### ISSUE TITLE
readFromSecureStore() return object type instead of SecureStorableResultType

### ISSUE THREAD

**Issue by eriksargent** [matthewpalmer/Locksmith#76]
I really like the new feature where you can create a struct, respond to a few protocols, and return the data variable and Locksmith will automatically be able to save the object. However, if it could also fetch the object, that would be even better. It is nice to be able to have Locksmith fetch the object, but I still have to manually pull my properties out of the data object and it seems like that process could be improved. 

For example, if the structs were instead subclasses of NSObject, then they could work with the `setValue forKey` and `valueForKey` functions. Then the `data` property could return a list of strings of the key names for all properties that will be stored in the keychain. From there, the createInSecureStore could piece together the data to be stored by iterating over the strings in `data` and calling `valueForKey` on each. Then when reading from the keychain with `readFromSecureStore` the function would return an object of your custom type and your properties would be populated with `setValue forKey` on each property that is in `data` and was returned from the keychain.

This would however require a few changes, so there's probably a better and more elegant way to make this possible. What do you think?

**Comment by matthewpalmer** [comment]
Thanks for the feedback! I really like the idea.

My original intention was to be able to use generics to do this, i.e. the user could specify the type of the data to be saved and read back. Unfortunately, I haven't yet been able to come up with the right way to do this (always end up getting stuck by `Protocol 'GenericProtocol' can only be used as a generic constraint because it has Self or associated type requirements.` errors).

I'm also sort of hoping there will be some language support for protocol generics (rather than using type aliases) in the future, which would make this easier.

If/when I do the next big release, this will definitely be one of the goals, so feel free to make suggestions/submit PRs that use generics to accomplish this :)

Closing this issue because there aren't really any actions to make immediately, but feel free to reopen at any point 👍
